export const SMILES = [
    {
        emoji: '😀',
        dec: 128512,
        hex: 'x1F600',
        name: 'GRINNING FACE',
    },
    {
        emoji: '😁',
        dec: 128513,
        hex: 'x1F601',
        name: 'GRINNING FACE WITH SMILING EYES',
    },
    {
        emoji: '😂',
        dec: 128514,
        hex: 'x1F602',
        name: 'FACE WITH TEARS OF JOY',
    },
    {
        emoji: '😃',
        dec: 128515,
        hex: 'x1F603',
        name: 'SMILING FACE WITH OPEN MOUTH',
    },
    {
        emoji: '😄',
        dec: 128516,
        hex: 'x1F604',
        name: 'SMILING FACE WITH OPEN MOUTH AND SMILING EYES',
    },
    {
        emoji: '😅',
        dec: 128517,
        hex: 'x1F605',
        name: 'SMILING FACE WITH OPEN MOUTH AND COLD SWEAT',
    },
    {
        emoji: '😆',
        dec: 128518,
        hex: 'x1F606',
        name: 'SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES',
    },
    {
        emoji: '😇',
        dec: 128519,
        hex: 'x1F607',
        name: 'SMILING FACE WITH HALO',
    },
    {
        emoji: '😈',
        dec: 128520,
        hex: 'x1F608',
        name: 'SMILING FACE WITH HORNS',
    },
    {
        emoji: '😉',
        dec: 128521,
        hex: 'x1F609',
        name: 'WINKING FACE',
    },
    {
        emoji: '😊',
        dec: 128522,
        hex: 'x1F60A',
        name: 'SMILING FACE WITH SMILING EYES',
    },
    {
        emoji: '😋',
        dec: 128523,
        hex: 'x1F60B',
        name: 'FACE SAVOURING DELICIOUS FOOD',
    },
    {
        emoji: '😌',
        dec: 128524,
        hex: 'x1F60C',
        name: 'RELIEVED FACE',
    },
    {
        emoji: '😍',
        dec: 128525,
        hex: 'x1F60D',
        name: 'SMILING FACE WITH HEART-SHAPED EYES',
    },
    {
        emoji: '😎',
        dec: 128526,
        hex: 'x1F60E',
        name: 'SMILING FACE WITH SUNGLASSES',
    },
    {
        emoji: '😏',
        dec: 128527,
        hex: 'x1F60F',
        name: 'SMIRKING FACE',
    },
    {
        emoji: '😐',
        dec: 128528,
        hex: 'x1F610',
        name: 'NEUTRAL FACE',
    },
    {
        emoji: '😑',
        dec: 128529,
        hex: 'x1F611',
        name: 'EXPRESSIONLESS FACE',
    },
    {
        emoji: '😒',
        dec: 128530,
        hex: 'x1F612',
        name: 'UNAMUSED FACE',
    },
    {
        emoji: '😓',
        dec: 128531,
        hex: 'x1F613',
        name: 'FACE WITH COLD SWEAT',
    },
    {
        emoji: '😔',
        dec: 128532,
        hex: 'x1F614',
        name: 'PENSIVE FACE',
    },
    {
        emoji: '😕',
        dec: 128533,
        hex: 'x1F615',
        name: 'CONFUSED FACE',
    },
    {
        emoji: '😖',
        dec: 128534,
        hex: 'x1F616',
        name: 'CONFOUNDED FACE',
    },
    {
        emoji: '😗',
        dec: 128535,
        hex: 'x1F617',
        name: 'KISSING FACE',
    },
    {
        emoji: '😘',
        dec: 128536,
        hex: 'x1F618',
        name: 'FACE THROWING A KISS',
    },
    {
        emoji: '😙',
        dec: 128537,
        hex: 'x1F619',
        name: 'KISSING FACE WITH SMILING EYES',
    },
    {
        emoji: '😚',
        dec: 128538,
        hex: 'x1F61A',
        name: 'KISSING FACE WITH CLOSED EYES',
    },
    {
        emoji: '😛',
        dec: 128539,
        hex: 'x1F61B',
        name: 'FACE WITH STUCK-OUT TONGUE',
    },
    {
        emoji: '😜',
        dec: 128540,
        hex: 'x1F61C',
        name: 'FACE WITH STUCK-OUT TONGUE AND WINKING EYE',
    },
    {
        emoji: '😝',
        dec: 128541,
        hex: 'x1F61D',
        name: 'FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES',
    },
    {
        emoji: '😞',
        dec: 128542,
        hex: 'x1F61E',
        name: 'DISAPPOINTED FACE',
    },
    {
        emoji: '😟',
        dec: 128543,
        hex: 'x1F61F',
        name: 'WORRIED FACE',
    },
    {
        emoji: '😠',
        dec: 128544,
        hex: 'x1F620',
        name: 'ANGRY FACE',
    },
    {
        emoji: '😡',
        dec: 128545,
        hex: 'x1F621',
        name: 'POUTING FACE',
    },
    {
        emoji: '😢',
        dec: 128546,
        hex: 'x1F622',
        name: 'CRYING FACE',
    },
    {
        emoji: '😣',
        dec: 128547,
        hex: 'x1F623',
        name: 'PERSEVERING FACE',
    },
    {
        emoji: '😤',
        dec: 128548,
        hex: 'x1F624',
        name: 'FACE WITH LOOK OF TRIUMPH',
    },
    {
        emoji: '😥',
        dec: 128549,
        hex: 'x1F625',
        name: 'DISAPPOINTED BUT RELIEVED FACE',
    },
    {
        emoji: '😦',
        dec: 128550,
        hex: 'x1F626',
        name: 'FROWNING FACE WITH OPEN MOUTH',
    },
    {
        emoji: '😧',
        dec: 128551,
        hex: 'x1F627',
        name: 'ANGUISHED FACE',
    },
    {
        emoji: '😨',
        dec: 128552,
        hex: 'x1F628',
        name: 'FEARFUL FACE',
    },
    {
        emoji: '😩',
        dec: 128553,
        hex: 'x1F629',
        name: 'WEARY FACE',
    },
    {
        emoji: '😪',
        dec: 128554,
        hex: 'x1F62A',
        name: 'SLEEPY FACE',
    },
    {
        emoji: '😫',
        dec: 128555,
        hex: 'x1F62B',
        name: 'TIRED FACE',
    },
    {
        emoji: '😬',
        dec: 128556,
        hex: 'x1F62C',
        name: 'GRIMACING FACE',
    },
    {
        emoji: '😭',
        dec: 128557,
        hex: 'x1F62D',
        name: 'LOUDLY CRYING FACE',
    },
    {
        emoji: '😮',
        dec: 128558,
        hex: 'x1F62E',
        name: 'FACE WITH OPEN MOUTH',
    },
    {
        emoji: '😯',
        dec: 128559,
        hex: 'x1F62F',
        name: 'HUSHED FACE',
    },
    {
        emoji: '😰',
        dec: 128560,
        hex: 'x1F630',
        name: 'FACE WITH OPEN MOUTH AND COLD SWEAT',
    },
    {
        emoji: '😱',
        dec: 128561,
        hex: 'x1F631',
        name: 'FACE SCREAMING IN FEAR',
    },
    {
        emoji: '😲',
        dec: 128562,
        hex: 'x1F632',
        name: 'ASTONISHED FACE',
    },
    {
        emoji: '😳',
        dec: 128563,
        hex: 'x1F633',
        name: 'FLUSHED FACE',
    },
    {
        emoji: '😴',
        dec: 128564,
        hex: 'x1F634',
        name: 'SLEEPING FACE',
    },
    {
        emoji: '😵',
        dec: 128565,
        hex: 'x1F635',
        name: 'DIZZY FACE',
    },
    {
        emoji: '😶',
        dec: 128566,
        hex: 'x1F636',
        name: 'FACE WITHOUT MOUTH',
    },
    {
        emoji: '😷',
        dec: 128567,
        hex: 'x1F637',
        name: 'FACE WITH MEDICAL MASK',
    },
    {
        emoji: '🙁',
        dec: 128577,
        hex: 'x1F641',
        name: 'SLIGHTLY FROWNING FACE',
    },
    {
        emoji: '🙂',
        dec: 128578,
        hex: 'x1F642',
        name: 'SLIGHTLY SMILING FACE',
    },
    {
        emoji: '🙃',
        dec: 128579,
        hex: 'x1F643',
        name: 'UPSIDE-DOWN FACE',
    },
    {
        emoji: '🙄',
        dec: 128580,
        hex: 'x1F644',
        name: 'FACE WITH ROLLING EYES',
    },
    {
        emoji: '🤐',
        dec: 129296,
        hex: 'x1F910',
        name: 'ZIPPER-MOUTH FACE',
    },
    {
        emoji: '🤑',
        dec: 129297,
        hex: 'x1F911',
        name: 'MONEY-MOUTH FACE',
    },
    {
        emoji: '🤒',
        dec: 129298,
        hex: 'x1F912',
        name: 'FACE WITH THERMOMETER',
    },
    {
        emoji: '🤓',
        dec: 129299,
        hex: 'x1F913',
        name: 'NERD FACE',
    },
    {
        emoji: '🤔',
        dec: 129300,
        hex: 'x1F914',
        name: 'THINKING FACE',
    },
    {
        emoji: '🤕',
        dec: 129301,
        hex: 'x1F915',
        name: 'FACE WITH HEAD-BANDAGE',
    },
    {
        emoji: '🤗',
        dec: 129303,
        hex: 'x1F917',
        name: 'HUGGING FACE',
    },
    {
        emoji: '🤠',
        dec: 129312,
        hex: 'x1F920',
        name: 'COWBOY HAT FACE',
    },
    {
        emoji: '🤢',
        dec: 129314,
        hex: 'x1F922',
        name: 'NAUSEATED FACE',
    },
    {
        emoji: '🤣',
        dec: 129315,
        hex: 'x1F923',
        name: 'ROLLING ON THE FLOOR LAUGHING',
    },
    {
        emoji: '🤤',
        dec: 129316,
        hex: 'x1F924',
        name: 'DROOLING FACE',
    },
    {
        emoji: '🤥',
        dec: 129317,
        hex: 'x1F925',
        name: 'LYING FACE',
    },
    {
        emoji: '🤧',
        dec: 129319,
        hex: 'x1F927',
        name: 'SNEEZING FACE',
    },
    {
        emoji: '🤨',
        dec: 129320,
        hex: 'x1F928',
        name: 'FACE WITH RAISED EYEBROW',
    },
    {
        emoji: '🤩',
        dec: 129321,
        hex: 'x1F929',
        name: 'GRINNING FACE WITH STAR EYES',
    },
    {
        emoji: '🤪',
        dec: 129322,
        hex: 'x1F92A',
        name: 'ZANY FACE',
    },
    {
        emoji: '🤫',
        dec: 129323,
        hex: 'x1F92B',
        name: 'SHUSHING FACE',
    },
    {
        emoji: '🤭',
        dec: 129325,
        hex: 'x1F92D',
        name: 'FACE WITH HAND OVER MOUTH',
    },
    {
        emoji: '🤮',
        dec: 129326,
        hex: 'x1F92E',
        name: 'FACE VOMITING',
    },
    {
        emoji: '🤯',
        dec: 129327,
        hex: 'x1F92F',
        name: 'EXPLODING HEAD',
    },
    {
        emoji: '🥰',
        dec: 129392,
        hex: 'x1F970',
        name: 'SMILING FACE WITH HEARTS',
    },
    {
        emoji: '🥱',
        dec: 129393,
        hex: 'x1F971',
        name: 'YAWNING FACE',
    },
    {
        emoji: '🥳',
        dec: 129395,
        hex: 'x1F973',
        name: 'PARTYING FACE',
    },
    {
        emoji: '🥴',
        dec: 129396,
        hex: 'x1F974',
        name: 'WOOZY FACE',
    },
    {
        emoji: '🥵',
        dec: 129397,
        hex: 'x1F975',
        name: 'HOT FACE',
    },
    {
        emoji: '🥶',
        dec: 129398,
        hex: 'x1F976',
        name: 'COLD FACE',
    },
    {
        emoji: '🥺',
        dec: 129402,
        hex: 'x1F97A',
        name: 'PLEADING FACE',
    },
    {
        emoji: '🧐',
        dec: 129488,
        hex: 'x1F9D0',
        name: 'FACE WITH MONOCLE',
    },
    {
        emoji: '😸',
        dec: 128568,
        hex: 'x1F638',
        name: 'GRINNING CAT FACE WITH SMILING EYES',
    },
    {
        emoji: '😹',
        dec: 128569,
        hex: 'x1F639',
        name: 'CAT FACE WITH TEARS OF JOY',
    },
    {
        emoji: '😺',
        dec: 128570,
        hex: 'x1F63A',
        name: 'SMILING CAT FACE WITH OPEN MOUTH',
    },
    {
        emoji: '😻',
        dec: 128571,
        hex: 'x1F63B',
        name: 'SMILING CAT FACE WITH HEART-SHAPED EYES',
    },
    {
        emoji: '😼',
        dec: 128572,
        hex: 'x1F63C',
        name: 'CAT FACE WITH WRY SMILE',
    },
    {
        emoji: '😽',
        dec: 128573,
        hex: 'x1F63D',
        name: 'KISSING CAT FACE WITH CLOSED EYES',
    },
    {
        emoji: '😾',
        dec: 128574,
        hex: 'x1F63E',
        name: 'POUTING CAT FACE',
    },
    {
        emoji: '😿',
        dec: 128575,
        hex: 'x1F63F',
        name: 'CRYING CAT FACE',
    },
    {
        emoji: '🙀',
        dec: 128576,
        hex: 'x1F640',
        name: 'WEARY CAT FACE',
    },
    {
        emoji: '🙈',
        dec: 128584,
        hex: 'x1F648',
        name: 'SEE-NO-EVIL MONKEY',
    },
    {
        emoji: '🙉',
        dec: 128585,
        hex: 'x1F649',
        name: 'HEAR-NO-EVIL MONKEY',
    },
    {
        emoji: '🙊',
        dec: 128586,
        hex: 'x1F64A',
        name: 'SPEAK-NO-EVIL MONKEY',
    },
    {
        emoji: '👿',
        dec: 128127,
        hex: 'x1F47F',
        name: 'ANGRY FACE WITH HORNS',
    },
    {
        emoji: '💀',
        dec: 128128,
        hex: 'x1F480',
        name: 'SKULL',
    },
    {
        emoji: '🤬',
        dec: 129324,
        hex: 'x1F92C',
        name: 'FACE WITH SYMBOLS ON MOUTH',
    },
];

export const HANDS = [
    {
        emoji: '✋',
        dec: 9995,
        hex: 'x270B',
        name: 'RAISED HAND',
    },
    {
        emoji: '👋',
        dec: 128075,
        hex: 'x1F44B',
        name: 'WAVING HAND',
    },
    {
        emoji: '🖐',
        dec: 128400,
        hex: 'x1F590',
        name: 'HAND WITH FINGERS SPLAYED',
    },
    {
        emoji: '🖖',
        dec: 128406,
        hex: 'x1F596',
        name: 'VULCAN SALUTE',
    },
    {
        emoji: '🤚',
        dec: 129306,
        hex: 'x1F91A',
        name: 'RAISED BACK OF HAND',
    },
    {
        emoji: '☝',
        dec: 9757,
        hex: 'x261D',
        name: 'INDEX POINTING UP',
    },
    {
        emoji: '👆',
        dec: 128070,
        hex: 'x1F446',
        name: 'BACKHAND INDEX POINTING UP',
    },
    {
        emoji: '👇',
        dec: 128071,
        hex: 'x1F447',
        name: 'BACKHAND INDEX POINTING DOWN',
    },
    {
        emoji: '👈',
        dec: 128072,
        hex: 'x1F448',
        name: 'BACKHAND INDEX POINTING LEFT',
    },
    {
        emoji: '👉',
        dec: 128073,
        hex: 'x1F449',
        name: 'BACKHAND INDEX POINTING RIGHT',
    },
    {
        emoji: '🖕',
        dec: 128405,
        hex: 'x1F595',
        name: 'MIDDLE FINGER',
    },
    {
        emoji: '✊',
        dec: 9994,
        hex: 'x270A',
        name: 'RAISED FIST',
    },
    {
        emoji: '👊',
        dec: 128074,
        hex: 'x1F44A',
        name: 'ONCOMING FIST',
    },
    {
        emoji: '👍',
        dec: 128077,
        hex: 'x1F44D',
        name: 'THUMBS UP',
    },
    {
        emoji: '👎',
        dec: 128078,
        hex: 'x1F44E',
        name: 'THUMBS DOWN',
    },
    {
        emoji: '🤛',
        dec: 129307,
        hex: 'x1F91B',
        name: 'LEFT-FACING FIST',
    },
    {
        emoji: '🤜',
        dec: 129308,
        hex: 'x1F91C',
        name: 'RIGHT-FACING FIST',
    },
    {
        emoji: '✌',
        dec: 9996,
        hex: 'x270C',
        name: 'VICTORY HAND',
    },
    {
        emoji: '👌',
        dec: 128076,
        hex: 'x1F44C',
        name: 'OK HAND',
    },
    {
        emoji: '🤏',
        dec: 129295,
        hex: 'x1F90F',
        name: 'PINCHING HAND',
    },
    {
        emoji: '🤘',
        dec: 129304,
        hex: 'x1F918',
        name: 'SIGN OF THE HORNS',
    },
    {
        emoji: '🤙',
        dec: 129305,
        hex: 'x1F919',
        name: 'CALL ME HAND',
    },
    {
        emoji: '🤞',
        dec: 129310,
        hex: 'x1F91E',
        name: 'CROSSED FINGERS',
    },
    {
        emoji: '🤟',
        dec: 129311,
        hex: 'x1F91F',
        name: 'LOVE-YOU GESTURE',
    },
    {
        emoji: '✍',
        dec: 9997,
        hex: 'x270D',
        name: 'WRITING HAND',
    },
    {
        emoji: '👏',
        dec: 128079,
        hex: 'x1F44F',
        name: 'CLAPPING HANDS',
    },
    {
        emoji: '👐',
        dec: 128080,
        hex: 'x1F450',
        name: 'OPEN HANDS',
    },
    {
        emoji: '💅',
        dec: 128133,
        hex: 'x1F485',
        name: 'NAIL POLISH',
    },
    {
        emoji: '🤝',
        dec: 129309,
        hex: 'x1F91D',
        name: 'HANDSHAKE',
    },
    {
        emoji: '🤝',
        dec: 129309,
        hex: 'x1F91D',
        name: 'HANDSHAKE',
    },
    {
        emoji: '🤲',
        dec: 129330,
        hex: 'x1F932',
        name: 'PALMS UP TOGETHER',
    },
    {
        emoji: '🤳',
        dec: 129331,
        hex: 'x1F933',
        name: 'SELFIE',
    },
];

export const PEAPLE = [
    {
        emoji: '👮',
        dec: 128110,
        hex: 'x1F46E',
        name: 'Police',
    },
    {
        emoji: '👯',
        dec: 128111,
        hex: 'x1F46F',
        name: 'Bunnies',
    },
    {
        emoji: '👰',
        dec: 128112,
        hex: 'x1F470',
        name: 'Bride',
    },
    {
        emoji: '👲',
        dec: 128114,
        hex: 'x1F472',
        name: 'Man Gua pi mao',
    },
    {
        emoji: '👳',
        dec: 128115,
        hex: 'x1F473',
        name: 'Man turban',
    },
    {
        emoji: '👷',
        dec: 128119,
        hex: 'x1F477',
        name: 'Construction worker',
    },
    {
        emoji: '👸',
        dec: 128120,
        hex: 'x1F478',
        name: 'Princess',
    },
    {
        emoji: '🕴',
        dec: 128372,
        hex: 'x1F574',
        name: 'Buisness suit',
    },
    {
        emoji: '🕵',
        dec: 128373,
        hex: 'x1F575',
        name: 'Detective or Spy',
    },
    {
        emoji: '💁',
        dec: 128129,
        hex: 'x1F481',
        name: 'Helpdesk',
    },
    {
        emoji: '💂',
        dec: 128130,
        hex: 'x1F482',
        name: 'Guardsman',
    },
    {
        emoji: '💃',
        dec: 128131,
        hex: 'x1F483',
        name: 'Dancer',
    },
    {
        emoji: '🤴',
        dec: 129332,
        hex: 'x1F934',
        name: 'Prince',
    },
    {
        emoji: '🤵',
        dec: 129333,
        hex: 'x1F935',
        name: 'Man in tuxedo',
    },
    {
        emoji: '👪',
        dec: 128106,
        hex: 'x1F46A',
        name: 'Family',
    },
    {
        emoji: '👫',
        dec: 128107,
        hex: 'x1F46B',
        name: 'Man and woman',
    },
    {
        emoji: '👬',
        dec: 128108,
        hex: 'x1F46C',
        name: 'Two men',
    },
    {
        emoji: '👭',
        dec: 128109,
        hex: 'x1F46D',
        name: 'Two women',
    },
    {
        emoji: '💏',
        dec: 128143,
        hex: 'x1F48F',
        name: 'Kiss',
    },
    {
        emoji: '💑',
        dec: 128145,
        hex: 'x1F491',
        name: 'Love',
    },
    {
        emoji: '🤰',
        dec: 129328,
        hex: 'x1F930',
        name: 'Pregnant',
    },
    {
        emoji: '🤱',
        dec: 129329,
        hex: 'x1F931',
        name: 'Breast feeding',
    },
    {
        emoji: '👤',
        dec: 128100,
        hex: 'x1F464',
        name: 'Bust',
    },
    {
        emoji: '👥',
        dec: 128101,
        hex: 'x1F465',
        name: 'Busts',
    },
    {
        emoji: '👦',
        dec: 128102,
        hex: 'x1F466',
        name: 'Boy',
    },
    {
        emoji: '👧',
        dec: 128103,
        hex: 'x1F467',
        name: 'Girl',
    },
    {
        emoji: '👨',
        dec: 128104,
        hex: 'x1F468',
        name: 'Man',
    },
    {
        emoji: '👩',
        dec: 128105,
        hex: '1F469',
        name: 'Woman',
    },
    {
        emoji: '👱',
        dec: 128113,
        hex: 'x1F471',
        name: 'Person blond',
    },
    {
        emoji: '👴',
        dec: 128116,
        hex: 'x1F474',
        name: 'Older man',
    },
    {
        emoji: '👵',
        dec: 128117,
        hex: 'x1F475',
        name: 'Older woman',
    },
    {
        emoji: '👶',
        dec: 128118,
        hex: 'x1F476',
        name: 'Baby',
    },
    {
        emoji: '🕺',
        dec: 128378,
        hex: 'x1F57A',
        name: 'Man dancing',
    },
    {
        emoji: '🧍',
        dec: 129485,
        hex: 'x1F9CD',
        name: 'Person standing',
    },
    {
        emoji: '🧎',
        dec: 129486,
        hex: 'x1F9CE',
        name: 'Person kneeling',
    },
    {
        emoji: '🧑',
        dec: 129489,
        hex: 'x1F9D1',
        name: 'Adult',
    },
    {
        emoji: '🧒',
        dec: 129490,
        hex: 'x1F9D2',
        name: 'Child',
    },
    {
        emoji: '🧓',
        dec: 129491,
        hex: 'x1F9D3',
        name: 'Older adult',
    },
    {
        emoji: '🧔',
        dec: 129492,
        hex: 'x1F9D4',
        name: 'Bearded man',
    },
    {
        emoji: '🧕',
        dec: 129493,
        hex: 'x1F9D5',
        name: 'Headsharf',
    },
    {
        emoji: '🧖',
        dec: 129494,
        hex: 'x1F9D6',
        name: 'Steamy room',
    },
    {
        emoji: '🧗',
        dec: 129495,
        hex: '1F9D7',
        name: 'Climbing',
    },
    {
        emoji: '🧘',
        dec: 129496,
        hex: 'x1F9D8',
        name: 'Lotus position',
    },
    {
        emoji: '🦰',
        dec: 129456,
        hex: 'x1F9B0',
        name: 'Red hair',
    },
    {
        emoji: '🦱',
        dec: 129457,
        hex: 'x1F9B1',
        name: 'Curly hair',
    },
    {
        emoji: '🦲',
        dec: 129458,
        hex: 'x1F9B2',
        name: 'Bald',
    },
    {
        emoji: '🦳',
        dec: 129459,
        hex: 'x1F9B3',
        name: 'White hair',
    },
    {
        emoji: '💆',
        dec: 128134,
        hex: 'x1F486',
        name: 'Face massage',
    },
    {
        emoji: '💇',
        dec: 128135,
        hex: 'x1F487',
        name: 'Haircut',
    },
    {
        emoji: '🙅',
        dec: 128581,
        hex: 'x1F645',
        name: 'No good',
    },
    {
        emoji: '🙆',
        dec: 128582,
        hex: 'x1F646',
        name: 'OK',
    },
    {
        emoji: '🙇',
        dec: 128583,
        hex: 'x1F647',
        name: 'Bowing deeply',
    },
    {
        emoji: '🙋',
        dec: 128587,
        hex: 'x1F64B',
        name: 'Raised hand',
    },
    {
        emoji: '🙌',
        dec: 128588,
        hex: 'x1F64C',
        name: 'Celebration',
    },
    {
        emoji: '🙍',
        dec: 128589,
        hex: 'x1F64D',
        name: 'Frowning',
    },
    {
        emoji: '🙎',
        dec: 128590,
        hex: 'x1F64E',
        name: 'Pouting face',
    },
    {
        emoji: '🙏',
        dec: 128591,
        hex: 'x1F64F',
        name: 'Folded hands',
    },
    {
        emoji: '🤦',
        dec: 129318,
        hex: 'x1F926',
        name: 'Face palm',
    },
    {
        emoji: '🤷',
        dec: 129335,
        hex: 'x1F937',
        name: 'Shrug',
    },
    {
        emoji: '🧏',
        dec: 129487,
        hex: 'x1F9CF',
        name: 'Deaf',
    },
    {
        emoji: '💬',
        dec: 128172,
        hex: 'x1F4AC',
        name: 'Speech Ballon',
    },
    {
        emoji: '💭',
        dec: 128173,
        hex: 'x1F4AD',
        name: 'Thought Ballon',
    },
    {
        emoji: '🗨',
        dec: 128488,
        hex: 'x1F5E8',
        name: 'Right speach bubble',
    },
    {
        emoji: '🗩',
        dec: 128489,
        hex: 'x1F5E9',
        name: 'Left speach bubble',
    },
    {
        emoji: '🗪',
        dec: 128490,
        hex: 'x1F5EA',
        name: 'Two speach bubbles',
    },
    {
        emoji: '🗫',
        dec: 128491,
        hex: 'x1F5EB',
        name: 'Three speach bubbles',
    },
    {
        emoji: '🗬',
        dec: 128492,
        hex: 'x1F5EC',
        name: 'Left thought bubble',
    },
    {
        emoji: '🗭',
        dec: 128493,
        hex: 'x1F5ED',
        name: 'Right thought bubble',
    },
    {
        emoji: '🗮',
        dec: 128494,
        hex: 'x1F5EE',
        name: 'Left anger bubble',
    },
    {
        emoji: '🗯',
        dec: 128495,
        hex: 'x1F5EF',
        name: 'Right anger bubble',
    },
    {
        emoji: '🗰',
        dec: 128496,
        hex: 'x1F5F0',
        name: 'Mood bubble',
    },
    {
        emoji: '🗱',
        dec: 128497,
        hex: 'x1F5F1',
        name: 'Lightning mood bubble',
    },
    {
        emoji: '🗲',
        dec: 128498,
        hex: 'x1F5F2',
        name: 'Lightning mood',
    },
    {
        emoji: '🎅',
        dec: 127877,
        hex: 'x1F385',
        name: 'Fatherr Christmas',
    },
    {
        emoji: '👹',
        dec: 128121,
        hex: 'x1F479',
        name: 'Japanese Ogre',
    },
    {
        emoji: '👺',
        dec: 128122,
        hex: 'x1F47A',
        name: 'Japanese Goblin',
    },
    {
        emoji: '👻',
        dec: 128123,
        hex: 'x1F47B',
        name: 'Ghost',
    },
    {
        emoji: '👼',
        dec: 128124,
        hex: 'x1F47C',
        name: 'Baby angel',
    },
    {
        emoji: '👽',
        dec: 128125,
        hex: 'x1F47D',
        name: 'Extraterrestial',
    },
    {
        emoji: '👾',
        dec: 128126,
        hex: 'x1F47E',
        name: 'Alien monster',
    },
    {
        emoji: '👿',
        dec: 128127,
        hex: 'x1F47F',
        name: 'Imp',
    },
    {
        emoji: '🤖',
        dec: 129302,
        hex: 'x1F916',
        name: 'Robot',
    },
    {
        emoji: '🤡',
        dec: 129313,
        hex: 'x1F921',
        name: 'Clown',
    },
    {
        emoji: '🤶',
        dec: 129334,
        hex: 'x1F936',
        name: 'Mother Christmas',
    },
    {
        emoji: '🦸',
        dec: 129464,
        hex: 'x1F9B8',
        name: 'Superhero',
    },
    {
        emoji: '🦹',
        dec: 129465,
        hex: 'x1F9B9',
        name: 'Supervillan',
    },
    {
        emoji: '🧙',
        dec: 129497,
        hex: 'x1F9D9',
        name: 'Mage',
    },
    {
        emoji: '🧚',
        dec: 129498,
        hex: 'x1F9DA',
        name: 'Fairy',
    },
    {
        emoji: '🧛',
        dec: 129499,
        hex: 'x1F9DB',
        name: 'Vampire',
    },
    {
        emoji: '🧜',
        dec: 129500,
        hex: 'x1F9DC',
        name: 'Merperson',
    },
    {
        emoji: '🧝',
        dec: 129501,
        hex: 'x1F9DD',
        name: 'Elf',
    },
    {
        emoji: '🧞',
        dec: 129502,
        hex: 'x1F9DE',
        name: 'Genie',
    },
    {
        emoji: '🧟',
        dec: 129503,
        hex: 'x1F9DF',
        name: 'Zombie',
    },
    {
        emoji: '👀',
        dec: 128064,
        hex: 'x1F440',
        name: 'Eyes',
    },
    {
        emoji: '👁',
        dec: 128065,
        hex: 'x1F441',
        name: 'Eye',
    },
    {
        emoji: '👂',
        dec: 128066,
        hex: 'x1F442',
        name: 'Ear',
    },
    {
        emoji: '👃',
        dec: 128067,
        hex: 'x1F443',
        name: 'Nose',
    },
    {
        emoji: '👄',
        dec: 128068,
        hex: 'x1F444',
        name: 'Mouth',
    },
    {
        emoji: '👅',
        dec: 128069,
        hex: 'x1F445',
        name: 'Tongue',
    },
    {
        emoji: '👣',
        dec: 128099,
        hex: 'x1F463',
        name: 'Footprints',
    },
    {
        emoji: '💪',
        dec: 128170,
        hex: 'x1F4AA',
        name: 'Flexed Biceps',
    },
    {
        emoji: '🦴',
        dec: 129460,
        hex: 'x1F9B4',
        name: 'Bone',
    },
    {
        emoji: '🦵',
        dec: 129461,
        hex: 'x1F9B5',
        name: 'Leg',
    },
    {
        emoji: '🦶',
        dec: 129462,
        hex: 'x1F9B6',
        name: 'Foot',
    },
    {
        emoji: '🦷',
        dec: 129463,
        hex: 'x1F9B7',
        name: 'Tooth',
    },
    {
        emoji: '🦻',
        dec: 129467,
        hex: 'x1F9BB',
        name: 'Hearing aid',
    },
    {
        emoji: '🦼',
        dec: 129468,
        hex: 'x1F9BC',
        name: 'Wheelchair motorized',
    },
    {
        emoji: '🦽',
        dec: 129469,
        hex: 'x1F9BD',
        name: 'Wheelchair manual',
    },
    {
        emoji: '🦾',
        dec: 129470,
        hex: 'x1F9BE',
        name: 'Mechanical arm',
    },
    {
        emoji: '🦿',
        dec: 129471,
        hex: 'x1F9BF',
        name: 'Mecanical leg',
    },
    {
        emoji: '🧠',
        dec: 129504,
        hex: 'x1F9E0',
        name: 'Brain',
    },
    {
        emoji: '🧡',
        dec: 129505,
        hex: 'x1F9E1',
        name: 'Heart',
    },
    {
        emoji: '💌',
        dec: 128140,
        hex: 'x1F48C',
        name: 'Love letter',
    },
    {
        emoji: '💒',
        dec: 128146,
        hex: 'x1F492',
        name: 'Wedding',
    },
    {
        emoji: '💓',
        dec: 128147,
        hex: 'x1F493',
        name: 'Beating heart',
    },
    {
        emoji: '💔',
        dec: 128148,
        hex: 'x1F494',
        name: 'Broken heart',
    },
    {
        emoji: '💕',
        dec: 128149,
        hex: 'x1F495',
        name: 'Two hearts',
    },
    {
        emoji: '💖',
        dec: 128150,
        hex: 'x1F496',
        name: 'Sparkling heart',
    },
    {
        emoji: '💗',
        dec: 128151,
        hex: 'x1F497',
        name: 'Growing heart',
    },
    {
        emoji: '💘',
        dec: 128152,
        hex: 'x1F498',
        name: 'Heart with arrow',
    },
    {
        emoji: '💙',
        dec: 128153,
        hex: 'x1F499',
        name: 'Blue heart',
    },
    {
        emoji: '💚',
        dec: 128154,
        hex: 'x1F49A',
        name: 'Green heart',
    },
    {
        emoji: '💛',
        dec: 128155,
        hex: 'x1F49B',
        name: 'Yellow heart',
    },
    {
        emoji: '💜',
        dec: 128156,
        hex: 'x1F49C',
        name: 'Purple heart',
    },
    {
        emoji: '💝',
        dec: 128157,
        hex: 'x1F49D',
        name: 'Heart with ribbon',
    },
    {
        emoji: '💞',
        dec: 128158,
        hex: 'x1F49E',
        name: 'Revolving hearts',
    },
    {
        emoji: '💟',
        dec: 128159,
        hex: 'x1F49F',
        name: 'Heart decoration',
    },
    {
        emoji: '🖤',
        dec: 128420,
        hex: 'x1F5A4',
        name: 'Black heart',
    },
    {
        emoji: '🤍',
        dec: 129293,
        hex: 'x1F90D',
        name: 'White heart',
    },
    {
        emoji: '🤎',
        dec: 129294,
        hex: 'x1F90E',
        name: 'Brown heart',
    },
    {
        emoji: '🩵',
        dec: 129653,
        hex: 'x1FA75',
        name: 'Light-blue heart',
    },
    {
        emoji: '🩶',
        dec: 129654,
        hex: 'x1FA76',
        name: 'Grey heart',
    },
    {
        emoji: '🩷',
        dec: 129655,
        hex: 'x1FA77',
        name: 'Pink heart',
    },
    {
        emoji: '💄',
        dec: 128132,
        hex: 'x1F484',
        name: 'Lipstick',
    },
    {
        emoji: '💅',
        dec: 128133,
        hex: 'x1F485',
        name: 'Nail polish',
    },
    {
        emoji: '💈',
        dec: 128136,
        hex: 'x1F488',
        name: 'Barber pole',
    },
    {
        emoji: '💉',
        dec: 128137,
        hex: 'x1F489',
        name: 'Syringe',
    },
    {
        emoji: '💊',
        dec: 128138,
        hex: 'x1F48A',
        name: 'Pill',
    },
    {
        emoji: '💋',
        dec: 128139,
        hex: 'x1F48B',
        name: 'Kiss mark',
    },
    {
        emoji: '💍',
        dec: 128141,
        hex: 'x1F48D',
        name: 'Ring',
    },
    {
        emoji: '💎',
        dec: 128142,
        hex: 'x1F48E',
        name: 'Gem stone',
    },
    {
        emoji: '💤',
        dec: 128164,
        hex: 'x1F4A4',
        name: 'Sleeping',
    },
    {
        emoji: '💩',
        dec: 128169,
        hex: 'x1F4A9',
        name: 'Pile of poo',
    },
    {
        emoji: '💫',
        dec: 128171,
        hex: 'x1F4AB',
        name: 'Dizzy',
    },
    {
        emoji: '🩸',
        dec: 129656,
        hex: 'x1FA78',
        name: 'Blood drop',
    },
    {
        emoji: '🩹',
        dec: 129657,
        hex: 'x1FA79',
        name: 'Plaster',
    },
    {
        emoji: '🩺',
        dec: 129658,
        hex: 'x1FA7A',
        name: 'Stethoscope',
    },
    {
        emoji: '🩻',
        dec: 129659,
        hex: 'x1FA7B',
        name: 'X-Ray',
    },
    {
        emoji: '🩼',
        dec: 129660,
        hex: 'x1FA7C',
        name: 'Crutch',
    },
];