export const SMILES = [
    {
        emoji: '😀',
        dec: 128512,
        hex: 'x1F600',
        name: 'GRINNING FACE',
    },
    {
        emoji: '😁',
        dec: 128513,
        hex: 'x1F601',
        name: 'GRINNING FACE WITH SMILING EYES',
    },
    {
        emoji: '😂',
        dec: 128514,
        hex: 'x1F602',
        name: 'FACE WITH TEARS OF JOY',
    },
    {
        emoji: '😃',
        dec: 128515,
        hex: 'x1F603',
        name: 'SMILING FACE WITH OPEN MOUTH',
    },
    {
        emoji: '😄',
        dec: 128516,
        hex: 'x1F604',
        name: 'SMILING FACE WITH OPEN MOUTH AND SMILING EYES',
    },
    {
        emoji: '😅',
        dec: 128517,
        hex: 'x1F605',
        name: 'SMILING FACE WITH OPEN MOUTH AND COLD SWEAT',
    },
    {
        emoji: '😆',
        dec: 128518,
        hex: 'x1F606',
        name: 'SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES',
    },
    {
        emoji: '😇',
        dec: 128519,
        hex: 'x1F607',
        name: 'SMILING FACE WITH HALO',
    },
    {
        emoji: '😈',
        dec: 128520,
        hex: 'x1F608',
        name: 'SMILING FACE WITH HORNS',
    },
    {
        emoji: '😉',
        dec: 128521,
        hex: 'x1F609',
        name: 'WINKING FACE',
    },
    {
        emoji: '😊',
        dec: 128522,
        hex: 'x1F60A',
        name: 'SMILING FACE WITH SMILING EYES',
    },
    {
        emoji: '😋',
        dec: 128523,
        hex: 'x1F60B',
        name: 'FACE SAVOURING DELICIOUS FOOD',
    },
    {
        emoji: '😌',
        dec: 128524,
        hex: 'x1F60C',
        name: 'RELIEVED FACE',
    },
    {
        emoji: '😍',
        dec: 128525,
        hex: 'x1F60D',
        name: 'SMILING FACE WITH HEART-SHAPED EYES',
    },
    {
        emoji: '😎',
        dec: 128526,
        hex: 'x1F60E',
        name: 'SMILING FACE WITH SUNGLASSES',
    },
    {
        emoji: '😏',
        dec: 128527,
        hex: 'x1F60F',
        name: 'SMIRKING FACE',
    },
    {
        emoji: '😐',
        dec: 128528,
        hex: 'x1F610',
        name: 'NEUTRAL FACE',
    },
    {
        emoji: '😑',
        dec: 128529,
        hex: 'x1F611',
        name: 'EXPRESSIONLESS FACE',
    },
    {
        emoji: '😒',
        dec: 128530,
        hex: 'x1F612',
        name: 'UNAMUSED FACE',
    },
    {
        emoji: '😓',
        dec: 128531,
        hex: 'x1F613',
        name: 'FACE WITH COLD SWEAT',
    },
    {
        emoji: '😔',
        dec: 128532,
        hex: 'x1F614',
        name: 'PENSIVE FACE',
    },
    {
        emoji: '😕',
        dec: 128533,
        hex: 'x1F615',
        name: 'CONFUSED FACE',
    },
    {
        emoji: '😖',
        dec: 128534,
        hex: 'x1F616',
        name: 'CONFOUNDED FACE',
    },
    {
        emoji: '😗',
        dec: 128535,
        hex: 'x1F617',
        name: 'KISSING FACE',
    },
    {
        emoji: '😘',
        dec: 128536,
        hex: 'x1F618',
        name: 'FACE THROWING A KISS',
    },
    {
        emoji: '😙',
        dec: 128537,
        hex: 'x1F619',
        name: 'KISSING FACE WITH SMILING EYES',
    },
    {
        emoji: '😚',
        dec: 128538,
        hex: 'x1F61A',
        name: 'KISSING FACE WITH CLOSED EYES',
    },
    {
        emoji: '😛',
        dec: 128539,
        hex: 'x1F61B',
        name: 'FACE WITH STUCK-OUT TONGUE',
    },
    {
        emoji: '😜',
        dec: 128540,
        hex: 'x1F61C',
        name: 'FACE WITH STUCK-OUT TONGUE AND WINKING EYE',
    },
    {
        emoji: '😝',
        dec: 128541,
        hex: 'x1F61D',
        name: 'FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES',
    },
    {
        emoji: '😞',
        dec: 128542,
        hex: 'x1F61E',
        name: 'DISAPPOINTED FACE',
    },
    {
        emoji: '😟',
        dec: 128543,
        hex: 'x1F61F',
        name: 'WORRIED FACE',
    },
    {
        emoji: '😠',
        dec: 128544,
        hex: 'x1F620',
        name: 'ANGRY FACE',
    },
    {
        emoji: '😡',
        dec: 128545,
        hex: 'x1F621',
        name: 'POUTING FACE',
    },
    {
        emoji: '😢',
        dec: 128546,
        hex: 'x1F622',
        name: 'CRYING FACE',
    },
    {
        emoji: '😣',
        dec: 128547,
        hex: 'x1F623',
        name: 'PERSEVERING FACE',
    },
    {
        emoji: '😤',
        dec: 128548,
        hex: 'x1F624',
        name: 'FACE WITH LOOK OF TRIUMPH',
    },
    {
        emoji: '😥',
        dec: 128549,
        hex: 'x1F625',
        name: 'DISAPPOINTED BUT RELIEVED FACE',
    },
    {
        emoji: '😦',
        dec: 128550,
        hex: 'x1F626',
        name: 'FROWNING FACE WITH OPEN MOUTH',
    },
    {
        emoji: '😧',
        dec: 128551,
        hex: 'x1F627',
        name: 'ANGUISHED FACE',
    },
    {
        emoji: '😨',
        dec: 128552,
        hex: 'x1F628',
        name: 'FEARFUL FACE',
    },
    {
        emoji: '😩',
        dec: 128553,
        hex: 'x1F629',
        name: 'WEARY FACE',
    },
    {
        emoji: '😪',
        dec: 128554,
        hex: 'x1F62A',
        name: 'SLEEPY FACE',
    },
    {
        emoji: '😫',
        dec: 128555,
        hex: 'x1F62B',
        name: 'TIRED FACE',
    },
    {
        emoji: '😬',
        dec: 128556,
        hex: 'x1F62C',
        name: 'GRIMACING FACE',
    },
    {
        emoji: '😭',
        dec: 128557,
        hex: 'x1F62D',
        name: 'LOUDLY CRYING FACE',
    },
    {
        emoji: '😮',
        dec: 128558,
        hex: 'x1F62E',
        name: 'FACE WITH OPEN MOUTH',
    },
    {
        emoji: '😯',
        dec: 128559,
        hex: 'x1F62F',
        name: 'HUSHED FACE',
    },
    {
        emoji: '😰',
        dec: 128560,
        hex: 'x1F630',
        name: 'FACE WITH OPEN MOUTH AND COLD SWEAT',
    },
    {
        emoji: '😱',
        dec: 128561,
        hex: 'x1F631',
        name: 'FACE SCREAMING IN FEAR',
    },
    {
        emoji: '😲',
        dec: 128562,
        hex: 'x1F632',
        name: 'ASTONISHED FACE',
    },
    {
        emoji: '😳',
        dec: 128563,
        hex: 'x1F633',
        name: 'FLUSHED FACE',
    },
    {
        emoji: '😴',
        dec: 128564,
        hex: 'x1F634',
        name: 'SLEEPING FACE',
    },
    {
        emoji: '😵',
        dec: 128565,
        hex: 'x1F635',
        name: 'DIZZY FACE',
    },
    {
        emoji: '😶',
        dec: 128566,
        hex: 'x1F636',
        name: 'FACE WITHOUT MOUTH',
    },
    {
        emoji: '😷',
        dec: 128567,
        hex: 'x1F637',
        name: 'FACE WITH MEDICAL MASK',
    },
    {
        emoji: '🙁',
        dec: 128577,
        hex: 'x1F641',
        name: '',
    },
    {
        emoji: '🙂',
        dec: 128578,
        hex: 'x1F642',
        name: '',
    },
    {
        emoji: '🙃',
        dec: 128579,
        hex: 'x1F643',
        name: '',
    },
    {
        emoji: '🙄',
        dec: 128580,
        hex: 'x1F644',
        name: '',
    },
    {
        emoji: '🤐',
        dec: 129296,
        hex: 'x1F910',
        name: '',
    },
    {
        emoji: '🤑',
        dec: 129297,
        hex: 'x1F911',
        name: '',
    },
    {
        emoji: '🤒',
        dec: 129298,
        hex: 'x1F912',
        name: '',
    },
    {
        emoji: '🤓',
        dec: 129299,
        hex: 'x1F913',
        name: '',
    },
    {
        emoji: '🤔',
        dec: 129300,
        hex: 'x1F914',
        name: '',
    },
    {
        emoji: '🤕',
        dec: 129301,
        hex: 'x1F915',
        name: '',
    },
    {
        emoji: '🤗',
        dec: 129303,
        hex: 'x1F917',
        name: '',
    },
    {
        emoji: '🤠',
        dec: 129312,
        hex: 'x1F920',
        name: '',
    },
    {
        emoji: '🤢',
        dec: 129314,
        hex: 'x1F922',
        name: '',
    },
    {
        emoji: '🤣',
        dec: 129315,
        hex: 'x1F923',
        name: '',
    },
    {
        emoji: '🤤',
        dec: 129316,
        hex: 'x1F924',
        name: '',
    },
    {
        emoji: '🤥',
        dec: 129317,
        hex: 'x1F925',
        name: '',
    },
    {
        emoji: '🤧',
        dec: 129319,
        hex: 'x1F927',
        name: '',
    },
    {
        emoji: '🤨',
        dec: 129320,
        hex: 'x1F928',
        name: '',
    },
    {
        emoji: '🤩',
        dec: 129321,
        hex: 'x1F929',
        name: '',
    },
    {
        emoji: '🤪',
        dec: 129322,
        hex: 'x1F92A',
        name: '',
    },
    {
        emoji: '🤫',
        dec: 129323,
        hex: 'x1F92B',
        name: '',
    },
    {
        emoji: '🤭',
        dec: 129325,
        hex: 'x1F92D',
        name: '',
    },
    {
        emoji: '🤮',
        dec: 129326,
        hex: 'x1F92E',
        name: '',
    },
    {
        emoji: '🤯',
        dec: 129327,
        hex: 'x1F92F',
        name: '',
    },
    {
        emoji: '🥰',
        dec: 129392,
        hex: 'x1F970',
        name: '',
    },
    {
        emoji: '🥱',
        dec: 129393,
        hex: 'x1F971',
        name: '',
    },
    {
        emoji: '🥳',
        dec: 129395,
        hex: 'x1F973',
        name: '',
    },
    {
        emoji: '🥴',
        dec: 129396,
        hex: 'x1F974',
        name: '',
    },
    {
        emoji: '🥵',
        dec: 129397,
        hex: 'x1F975',
        name: '',
    },
    {
        emoji: '🥶',
        dec: 129398,
        hex: 'x1F976',
        name: '',
    },
    {
        emoji: '🥺',
        dec: 129402,
        hex: 'x1F97A',
        name: '',
    },
    {
        emoji: '🧐',
        dec: 129488,
        hex: 'x1F9D0',
        name: '',
    },
    {
        emoji: '😸',
        dec: 128568,
        hex: 'x1F638',
        name: '',
    },
    {
        emoji: '😹',
        dec: 128569,
        hex: 'x1F639',
        name: '',
    },
    {
        emoji: '😺',
        dec: 128570,
        hex: 'x1F63A',
        name: '',
    },
    {
        emoji: '😻',
        dec: 128571,
        hex: 'x1F63B',
        name: '',
    },
    {
        emoji: '😼',
        dec: 128572,
        hex: 'x1F63C',
        name: '',
    },
    {
        emoji: '😽',
        dec: 128573,
        hex: 'x1F63D',
        name: '',
    },
    {
        emoji: '😾',
        dec: 128574,
        hex: 'x1F63E',
        name: '',
    },
    {
        emoji: '😿',
        dec: 128575,
        hex: 'x1F63F',
        name: '',
    },
    {
        emoji: '🙀',
        dec: 128576,
        hex: 'x1F640',
        name: '',
    },
    {
        emoji: '🙈',
        dec: 128584,
        hex: 'x1F648',
        name: '',
    },
    {
        emoji: '🙉',
        dec: 128585,
        hex: 'x1F649',
        name: '',
    },
    {
        emoji: '🙊',
        dec: 128586,
        hex: 'x1F64A',
        name: '',
    },
    {
        emoji: '👿',
        dec: 128127,
        hex: 'x1F47F',
        name: '',
    },
    {
        emoji: '💀',
        dec: 128128,
        hex: 'x1F480',
        name: '',
    },
    {
        emoji: '🤬',
        dec: 129324,
        hex: 'x1F92C',
        name: '',
    },
];